### ISSUE TITLE
Wrong articles URL

### ISSUE THREAD

**Issue by J05HI** [simonwuyts/portfolio#2]
Reproduction:
1. Go to https://www.simonwuyts.com/articles/
2. Reload the page
3. Click on one of the articles
4. Their URL is wrong. articles/ is duplicated.

![image](https://user-images.githubusercontent.com/16399787/81110957-99c67d80-8f1c-11ea-8d5f-0c4f299c5126.png)

**Comment by simonwuyts** [comment]
Thanks for noticing! I fixed it.

**Comment by J05HI** [comment]
@simonwuyts 
Thanks! I learned a lot form your portfolio 😉
